cc_library(
    name = "state",
    hdrs = ["state.h"],
    srcs = ["state.cc"],
    deps = [
    ],
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc"
    ],
    deps = [
        ":state",
    ],
)