cc_library(
    name = "game",
    hdrs = [
        "game.h"
    ],
    srcs = [
        "game.cc"
    ],
    deps = [
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":game",
    ],
)