cc_library(
    name = "grid",
    hdrs = [
        "grid.h",
    ],
    srcs = [
        "grid.cc",
    ],
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        ":grid",
    ],
)