cc_library(
    name = "position",
    hdrs = [
        "position.h"
    ],
    srcs = [
        "position.cc",
    ],
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc"
    ],
    deps = [
        ":position",
    ],
)