

cc_library(
    name = "track",
    hdrs = [
        "track.h"
    ],
    srcs = [
        "track.cc",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":track",
    ],
)