cc_library(
    name = "node",
    hdrs = [
        "node.h",
    ],
    srcs = [
        "node.cc",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":node",
    ],
)