cc_library(
    name = "scoreboard",
    hdrs = [
        "scoreboard.h",
    ],
    srcs = [
        "scoreboard.cc",
    ],
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        ":scoreboard",
    ],
)