cc_library(
    name = "polymer",
    hdrs = ["polymer.h"],
    srcs = [
        "polymer.cc",
    ],
    deps = [
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":polymer",
    ],
)